### ISSUE TITLE
Finish out pan-Arctic runs 

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/panarctic_underice_sunlight#1]
To finish out ECOLIGHT tasks, I want to have code that will run the RT models on multiple points for a transect, a grid, or a single point.  There are two components/tasks for this.  1. decode forcing data into a common format - 1D arrays; and 2. run RT model on these points in a distributed fashion.  These should be controlled by a single function so that the call looks like.

```
results = run_radiative_transfer(forcing_dataset_object, *, **kwargs)
```
or 
```
results = run_radiative_transfer(arr1, arr2, arr3,..., *, **kwargs)
```
or
```
results = run_radiative_transfer(dict_of_forcings, *, **kwargs)
```
**Focus on first option to use Pandas dataframe and xarray Dataset**

## RT model driver
- Wrapper for running RT model should skip cells with NaN
- Should allow for single or multiple time stamps
- Allow multiple outputs to be selected - _save for later_

## Decoder
- separate or combined decoder
- for grids needs to keep track of dimensions

## Tasks
- [ ] Create test forcing datasets for Pandas and xarray examples
- [ ] Create a single years test forcing using IS2 thickness
- [ ] Write decoders to transform forcing into 1D array for:
   - [ ] Pandas dataframe
   - [ ] Xarray dataset
   - [ ] numpy arrays (maybe)
- [ ] Write encoders to transform 1D results arrays into the same data structure as forcing provided
- [ ] Write wrapper to run RT model for multiple points
